# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 中文（默认语言）
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 李若冲的个人简历
  languageName: 中文
  weight: 1
  params:
    description: 产品开发者 + 算法工程师

# English
en:
  languageCode: en-us
  contentDir: content/en
  title: Ruochong Li (Arno) - Resume
  languageName: English
  weight: 2
  params:
    description: Product Creator + Algorithm Engineer
